### ISSUE TITLE
Include "Add Level" Button at the bottom also

### ISSUE THREAD

**Issue by aso1124** [newrelic/nr-labs-pathpoint#247]
This is a usability thing .. if you are adding a bunch of steps, the "Add Level" button is quickly lost at the top of the stage. Meanwhile the rest of the edit screen is structured to push you to keep moving down (as it were) - i.e. the add steps appear at the bottom, the add signals appear below the step. So knowing to go back to the top to add a level is counter-intuitive to the rest of the design of the edit mode.

In the screenshot, you can see that there's no visible help on how to add another level. Maybe the "Add Level" should also be fixed for scrolling, as the add stage is? Or have an add level at the bottom?

Also, when you do Add Level from the top, you should be positioned at the bottom where the new level is (at the moment, you stay at the top of the stage).

![Image](https://github.com/newrelic/nr-labs-hedgehog/assets/1786630/7ee8b74c-8d55-4de7-ac1a-bb4ab6fd9bcd)

**Comment by amit-y** [comment]
Remove the `Add level` button from the top of the stage and move it to the bottom
