### ISSUE TITLE
Two "Add a level" buttons appear in stage editor

### ISSUE THREAD

**Issue by JimHagan** [newrelic/nr-labs-pathpoint#312]
## Description

When using the stage editor it seems there are two different buttons named "add a level"

## Steps to Reproduce

Simply use the stage editor.  It happens every time.

## Expected Behaviour

Expect only a single button

<img width="405" alt="image" src="https://github.com/newrelic/nr-labs-hedgehog/assets/8333200/c70b0d5c-ceb2-4db7-9135-773f3c6f957a">

**Comment by aso1124** [comment]
Fixed in v1.2 by #247
