### ISSUE TITLE
Signal Selection - Account dropdown default

### ISSUE THREAD

**Issue by aso1124** [newrelic/nr-labs-pathpoint#416]
Default the account dropdown in the signal selection screen to be the same as the account used for the flow.

**Comment by khpeet** [comment]
or @amit-y ^

**Comment by amit-y** [comment]
I'm not sure if this one came from a user-reported bug, or if the intention was to add a fail-safe. I can explain the technical thought I had. Currently in the `signal-selection` nerdlet, [`accountId` is fetched from the platform](https://github.com/newrelic/nr-labs-pathpoint/blob/main/nerdlets/signal-selection/index.js#L53). The idea was to replace that with the `accountId` of the flow from where the nerdlet is called.

**Comment by aso1124** [comment]
We will remove the option to choose an account during the Create Flow; instead it will be auto-set to use the platform-selected account.

We need to replace account dropdowns in both Create Flow paths (create blank, import)

In both forms, replace the Account dropdown and label with the following text:
This flow will be created in **Account Name**. To change the account, close this overlay and change the account selected in the account dropdown.
