### ISSUE TITLE
Pathpoint V2 : Dashboard link to be added - Permlink / Hyperlink

### ISSUE THREAD

**Issue by Aparna-Mahesh** [newrelic/nr-labs-pathpoint#433]
In the earlier version of pathpoint , under Touchpoints we had an option general where we can enter dashboard permlink.
But in the newer version of Pathpoint V2 , we do not see any option to add dashboard.
Attached is the screenshot for reference.
<img width="790" alt="Pathpoint - Dashboard " src="https://github.com/user-attachments/assets/4b41594a-52e0-4ba4-989c-60d3d925e713">

**Comment by aso1124** [comment]
Hello @Aparna-Mahesh - you can now add a link to the Stage and Step levels of a Flow. The setting is available in the Flow Edit Mode: click on `...` and select `Settings`, which will open the configuration options for each, including the ability to add a link for more context (e.g. a dashboard). 

To open the link, once you have saved your changes and returned to the main flow view, click on the Stage name (which directly opens the link in a new window) or the Step name (which opens a context panel for the Step and includes the link out to the additional context).  

![image](https://github.com/user-attachments/assets/05fb606b-8820-46f3-9944-11d3c9655c1a)
